site_name: CD3 Documentation
repo_name: oracle-devrel/cd3-automation-toolkit
repo_url: https://github.com/oracle-devrel/cd3-automation-toolkit
nav:
  - Overview: CD3 Overview.md
  - Introduction: README.md
    
  - 'Launch CD3 container in OCI':
    - Single click container launch: singleclickdeploy.md

  - 'Launch CD3 container in Local ENV':
    - Prerequisites: prerequisites.md
    - Launch the container: Launch_Docker_container.md
  
  - 'Connect container to OCI tenancy':
    - Connect container to OCI tenancy: Connect_container_to_OCI_Tenancy.md
  
  - 'Toolkit Execution with CLI':
    - Overview: Workflows.md
    - Create resources in OCI using CLI (Greenfield Workflow): GreenField.md
    - Create Network resources-CLI: NetworkingScenariosGF.md
    - Create Compute Instances-CLI: ComputeGF.md
    - OPA integration: OPAForCompliance.md
    - Export Resources from OCI using CLI (Non-Greenfield Workflow): NonGreenField.md
    - Export Network resources-CLI: NetworkingScenariosNGF.md
    - Export Compute Instances-CLI: ComputeNGF.md

  - 'Toolkit execution with Jenkins':
    - Prerequisites: Workflows-jenkins.md
    - Overview: Intro-Jenkins.md
    - Create resources in OCI using Jenkins(Greenfield Workflow): GreenField-Jenkins.md
    - Create Network resources-Jenkins : NetworkingScenariosGF-Jenkins.md
    - Create compute Instances/OKE/SDDC/Database-Jenkins: GF-Jenkins.md
    - Provision multiple services together-Jenkins: multiple_options_GF-Jenkins.md
    - Export Resources from OCI using Jenkins(Non-Greenfield Workflow): NonGreenField-Jenkins.md
  - Synchronize Changes between CLI and Jenkins: cli_jenkins.md

  - 'Beyond the basics':
    - Grouping generated Terraform files: RestructuringOutDirectory.md
    - OCI Resource Manager Upload: ResourceManagerUpload.md
    - Support for Additional Attributes: SupportforAdditionalAttributes.md
    - Additional CIS Compliance Features: CISFeatures.md
    - CD3 Validator: SupportForCD3Validator.md
    - Migrate jobs to User's Jenkins environment: Jobs_Migration.md
    - Remote Management of Terraform State: remote_state.md

  - Upgrade to latest versions: Upgrade_Toolkit.md

  - 'Known Behaviour':
    - Expected Behaviour of CD3: KnownBehaviour.md
    - FAQs: FAQ.md
    
  - 'Videos & Tutorials':
    - Automation Toolkit Learning Videos: LearningVideos.md
    - Tutorials: tutorials.md
    
  
# Configuration
theme:
  name: material
  font:
    text: Open Sans
  features:
    - toc.integrate
    - navigation.indexes
    - navigation.expand
    - navigation.top
    - navigation.path
    - content.code.copy
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left  
  language: en
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: oracle
      primary: teal
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  icon:
    repo: fontawesome/brands/github
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  logo: oci.png  
extra_css:
- stylesheets/extra.css
  
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/oracle-devrel/cd3-automation-toolkit
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/playlist?list=PLPIzp-E1msrbJ3WawXVhzimQnLw5iafcp

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js #?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  
plugins:
  - search
  - blog
  

copyright: |
  &copy; 2022 <a href=""  target="_blank" rel="noopener">Mukund Murali</a>