site_name: CD3 Documentation
nav:
  - Introduction: README.md
    
  - 'Launch CD3 container in OCI':
    - Single click container launch: singleclickdeploy.md

  - 'Launch CD3 container in Local ENV':
    - Prerequisites: prerequisites.md
    - Launch the container: Launch_Docker_container.md
  
  - 'Connect container to OCI tenancy':
    - Connect container to OCI tenancy: Connect_container_to_OCI_Tenancy.md
  
  - 'Toolkit Execution with CLI':
    - Overview: Workflows.md
    - Create resources in OCI using CLI (Greenfield Workflow): GreenField.md
    - Create Network resources-CLI: NetworkingScenariosGF.md
    - Create Compute Instances-CLI: ComputeGF.md
    - OPA integration: OPAForCompliance.md
    - Export Resources from OCI using CLI (Non-Greenfield Workflow): NonGreenField.md
    - Export Network resources-CLI: NetworkingScenariosNGF.md
    - Export Compute Instances-CLI: ComputeNGF.md

  - 'Toolkit execution with Jenkins':
    - Prerequisites: Workflows-jenkins.md
    - Overview: Intro-Jenkins.md
    - Create resources in OCI using Jenkins(Greenfield Workflow): GreenField-Jenkins.md
    - Create Network resources-Jenkins : NetworkingScenariosGF-Jenkins.md
    - Create compute Instances/OKE/SDDC/Database-Jenkins: GF-Jenkins.md
    - Provision multiple services together-Jenkins: multiple_options_GF-Jenkins.md
    - Export Resources from OCI using Jenkins(Non-Greenfield Workflow): NonGreenField-Jenkins.md
  - Synchronize Changes between CLI and Jenkins: cli_jenkins.md

  - 'Beyond the basics':
    - Grouping generated Terraform files: RestructuringOutDirectory.md
    - OCI Resource Manager Upload: ResourceManagerUpload.md
    - Support for Additional Attributes: SupportforAdditionalAttributes.md
    - Additional CIS Compliance Features: CISFeatures.md
    - CD3 Validator: SupportForCD3Validator.md
    - Migrate jobs to User's Jenkins environment: Jobs_Migration.md
    - Remote Management of Terraform State: remote_state.md

  - Upgrade to latest versions: Upgrade_Toolkit.md

  - 'Known Behaviour':
    - Expected Behaviour of CD3: KnownBehaviour.md
    - FAQs: FAQ.md
    
  - 'Videos & Tutorials':
    - Automation Toolkit Learning Videos: LearningVideos.md
    - Tutorials: tutorials.md
    
    


theme: readthedocs