site_name: CD3 Documentation
repo_name: oracle-devrel/cd3-automation-toolkit
repo_url: https://github.com/oracle-devrel/cd3-automation-toolkit
nav:
  - Overview: 
    - CD3 Overview.md
    - Introduction: CD3 Overview.md  
    - Architecture: Architecture.md   
    - Services Supported: Services supported.md
    - Excel Templates: ExcelTemplates.md
      
  - Install CD3 :
    - install-cd3.md
    - Prerequisites: prerequisites.md
    - Launch CD3 Container:
      - seq_diagram.md
      - Resource Manager Stack: singleclickdeploy.md
      - Local Desktop: Launch_Docker_container.md
    - Connect CD3 container to OCI: Connect_container_to_OCI_Tenancy.md
  - Create, Update or Export TF with CD3 - CLI: 
    - Introduction: GreenField.md
    - Using CLI:
      - Before You Begin: Workflows.md
      - Creating Resources: GreenField.md
      - OPA integration: OPAForCompliance.md
      - Examples:
        - Create Network: NetworkingScenariosGF.md
        - Create Compute : ComputeGF.md
    - Using Jenkins: 
      - Before you Begin: Workflows-jenkins.md
      - Overview: Intro-Jenkins.md
      - Workflow: GreenField-Jenkins.md
      - Examples:
        - Create Network: NetworkingScenariosGF-Jenkins.md
        - Create Compute/OKE/SDDC/Database : GF-Jenkins.md
        - Provision multiple services together: multiple_options_GF-Jenkins.md
  - Create, Update or Export TF with CD3 - Jenkins:
    - Introduction: NonGreenField.md
    - Using CLI: 
      - Before you begin: Workflows.md
      - Workflow: NonGreenField.md
      - Examples:
        - Export Network: NetworkingScenariosNGF.md
        - Export Compute: ComputeNGF.md
    - Using Jenkins:
      - Before you begin:  Workflows-jenkins.md
      - Workflow: NonGreenField-Jenkins.md

      
    - Sync between CLI and Jenkins: cli_jenkins.md

  - Upgrade CD3:
    - Steps to Upgrade Toolkit: Upgrade_Toolkit.md

  - Additional Features:
    - Grouping generated TF files: RestructuringOutDirectory.md
    - OCI Resource Manager Upload: ResourceManagerUpload.md
    - Support for Additional Attrs: SupportforAdditionalAttributes.md
    - CIS Compliance Features: CISFeatures.md
    - CD3 Validator: SupportForCD3Validator.md
    - Migrate jobs to user's Jenkins: Jobs_Migration.md
    - Remote Management of Terraform State: remote_state.md
   


  - Troubleshooting:
    - Expected Behaviour: KnownBehaviour.md
    - Common Issues: CommonIssues.md
    - FAQs: FAQ.md
    
  - External References:
    - Learning Videos: LearningVideos.md
    - Tutorials: tutorials.md

  
# Configuration
theme:
  name: material
  font:
    text: Oracle Sans
  features:
    - toc.integrate
    - navigation.indexes
    - navigation.top
    - navigation.path
    - content.code.copy
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left  
  language: en
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: oracle
      primary: teal
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  icon:
    repo: fontawesome/brands/github
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  logo: images/oci.png  
extra_css:
- stylesheets/extra.css
  
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/oracle-devrel/cd3-automation-toolkit
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/playlist?list=PLPIzp-E1msrbJ3WawXVhzimQnLw5iafcp

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js #?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: #
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: Mukund
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  
plugins:
  - search
  - blog
  - section-index
  

copyright: |
  &copy; 2022 <a href=""  target="_blank" rel="noopener">Mukund Murali</a>